### ISSUE TITLE
manuallyAddFile will cause one additional redundant http image call

### ISSUE THREAD

**Issue by gfd6th** [rowanwins/vue-dropzone#192]
- Vue2-dropzone Version: 2.3.5 (`npm list --depth=0`)
- Node Version: 7.4 (`node -v`): 
- NPM Version 4.0.5(`npm -v`): 
- OS: osx 10.12.6

### Description:
manuallyAddFile will cause one additional redundant http image call
http://current-url/undefined

### Steps To Reproduce:
```html

<dropzone id="myVueDropzone"
              ref="dropzone"
              @vdropzone-mounted="loadExistingFiles"
      >

</dropzone>
```

```javascript

    data(){
      return {
            images: ['http://lorempixel.com/400/400', 'http://lorempixel.com/400/400']
        }
   },
    loadExistingFiles () {
        let images = JSON.parse(this.images)
        images.forEach(img => {
          let mockFile = {
            type: 'image/jpeg',
            name: img.split('/').pop(),
            size: 12345,
          }
          this.$refs.dropzone.manuallyAddFile(mockFile,  img,
            null,
            null,
            {
              dontSubstractMaxFiles: false,
              addToFiles: true,
            },
          )

        })
      },
```

**Comment by AlexanderYW** [comment]
Hmm just did some testing it seems like the method `manuallyAddFile` calls a dropzone method called `createThumbnailFromUrl` which seems to have updated its parameter since the parameters that gets provide now is no longer the used once in the official dropzone framework

A quick fix is just to remove line 148 in the index.vue file `this.dropzone.createThumbnailFromUrl....`, not sure if this have any consequences, but it seems to be a solution from the test's I have done so far

**Comment by rowanwins** [comment]
Thanks for that fix @AlexanderYW , we'll see if we'll add that change into v3.

**Comment by AlexanderYW** [comment]
@rowanwins I think it should, since most people dont want redundant http calls in production :)

**Comment by AlexanderYW** [comment]
@rowanwins if you haven't already implemented it in your local repo let me know, and I add it with my next PR :)

**Comment by rowanwins** [comment]
Gday @AlexanderYW 

I think this is resolved in the v3 branch which is where Im putting my efforts, if you'd like to implement it in the current branch go for it :)

**Comment by AlexanderYW** [comment]
Not sure if I'm wrong then correct me!, but from reading the source on dropzonejs line 1164 the `createThumbnailFromUrl` event does not have the parameters you are providing it :), am I wrong?
https://github.com/enyo/dropzone/blob/master/dist/dropzone.js#L1164

Also I think that `createThumbnailFromUrl` is kinda redundant since `emit("thumbnail", file, fileUrl)` does the job :)

**Comment by rowanwins** [comment]
Resolved in the now launched v3, check out the[ docs for info](https://rowanwins.github.io/vue-dropzone/docs/dist/#/installation) .
