### ISSUE TITLE
Confused with versioning/where did all the props go?

### ISSUE THREAD

**Issue by Cheaterflums** [rowanwins/vue-dropzone#256]
Hello, first I wanted to thank you for your great work!

My problem is the following:
I am currently using vue2-dropzone@3.0.0 and I just wanted to look up some prop names. But now the documentation changed completely and almost all of the props I used are gone. Are they now in the "options" prop or what happened to them? The "old" props like (accepted-file-types, max-number-of-files) are still working, but I guess they are deprecated now?

Furthermore I found out, that the newest version on npm is 3.0.0, but on git it is still 2.3.6, how can that be?

Thanks in advance!

**Comment by vrajroham** [comment]
Hey @Cheaterflums we recently redesigned the component from scratch which later released **v3.*** . You are right all the props now goes into `options` prop. Previously component was supporting direct props on component as well as options too. Due to this there were some glitches which we were not able to remove until redesigning the component. 

You can refer [props documentation](https://rowanwins.github.io/vue-dropzone/docs/dist/#/props) where you can get all the props. Now all options are supported which are specified by core dropzone component.

If you want to see what really changed/ enhanced from **v2.*** to *v3.** then, have a look on PR #205 (Complete read map)

Feel free to ask if you have more question!

Hv a great day!

**Comment by rowanwins** [comment]
Hi @Cheaterflums 

Pretty much everything @vrajroham said was spot on. The downside of the previous props approach was that we needed a prop for every option people wanted to use and this was getting way to cumbersome constantly dealing with pull requests etc. There were also some side effects of certain things not working like expected. Everything is now much simpler to maintain and provides more functionality so hopefully you can appreciate the changes :)

Where do you see git referencing v2.3.6?

**Comment by Cheaterflums** [comment]
Thank you for your answers @vrajroham @rowanwins, I really appreciate your help.

Under [https://github.com/rowanwins/vue-dropzone/releases](Releases) I only see version 2.3.6 and below

**Comment by vrajroham** [comment]
Actually we forgot to release the tag here, though on npm you can have latest build. Also thanks for pointing this, we will release latest tag here soon, so there will be no more confusion to users.
