### ISSUE TITLE
Large files thumb not loaded

### ISSUE THREAD

**Issue by muradsofiyev** [rowanwins/vue-dropzone#307]
When I upload 10mb+ image preview thumb not laod

**Comment by pkid169** [comment]
Actually this seems to be an issue with dropzone.js as well as I can replicate the same issue on dropzone demo page. We might be better off asking on dropzone github page...But any help from anyone who's managed to overcome this issue is highly appreciated!

**Comment by pkid169** [comment]
Ok, now I feel silly...There's an option with dropzone `maxThumbnailFilesize` that you can increase to have thumbnail generated for large file (http://www.dropzonejs.com/#config-maxThumbnailFilesize).

I guess the reason why dropzone is cautious about generating thumbnail for large file is because it takes a long time to get the base64 data. In my test, it takes at least 4-5 secs to generate the thumbnail for a file that's > 10 Mb, which means UX pretty much sucks. All in all, probably the thumbnail feature is not suppose to be for heavy file upload usage.

**Comment by rowanwins** [comment]
Thanks for sharing an answer @pkid169

**Comment by muradsofiyev** [comment]
I think maxThumbnailFilesize parametr add vue-dropzone too
