### ISSUE TITLE
vdropzone-queue-complete doesn't pass parameter arguments

### ISSUE THREAD

**Issue by TurboTobias** [rowanwins/vue-dropzone#386]
**Describe the bug**
It seems like `vdropzone-queue-complete` doesn't pass the arguments as stated in the dox (file, xhr, message).

**To reproduce**
Goto: https://codesandbox.io/s/xlr3lq2zzo
Open the console
Click `Process Queue`
See that the arguments (file, xhr, formData) are `undefined`

**Comment by rowanwins** [comment]
Hi @TurboTobias 

Thanks for the report, indeed it looks like the argument's aren't being passed through (see [here](https://github.com/rowanwins/vue-dropzone/blob/master/src/components/vue-dropzone.vue#L226-L228)).

This would make a great first task if anyone would like to take a look!

Cheers
R

**Comment by shraiysh** [comment]
I am starting my contribution for open-source and I want to handle this issue.

**Comment by rowanwins** [comment]
Great thank you @shraiysh - sing out if you need any help :)

**Comment by shraiysh** [comment]
Hey! @rowanwins Thanks for the support! I am only supposed to change the prototype of the function and emit value to

`this.dropzone.on('queuecomplete', function(file, xhr, formData) {
      vm.$emit('vdropzone-queue-complete',file, xhr, formData);
    })`

right? If this is not the case, could you please help me a little here!

**Comment by shraiysh** [comment]
Hey @rowanwins , how do I get the values inside the function in the line mentioned? Am I supposed to return a file from `vm.files`? Is it that I only have to change the prototype of the function and emit lines to suit it the docs just the way others are? Please help me out a little here!

**Comment by rowanwins** [comment]
HI @shraiysh 

Actually it turns out I've mislead you a little bit sorry!

The `queue-complete` event doesn't actually send any arguments, so it's our docs which are incorrect. If you look at the [original dropzone documentation](https://www.dropzonejs.com/#event-queuecomplete) you can see that.

So it's still a good beginner task, it's just a minor tweak to the [docs over here](https://github.com/rowanwins/vue-dropzone/blob/master/docs/src/pages/Events.vue#L36), you just need to remove the stuff between the `()`'s

Hopefully that makes sense :)

**Comment by shraiysh** [comment]
Thanks, @rowanwins I have made the change and submitted a pull request! Please let me know if there's an issue!

Have a nice day! :)

**Comment by rowanwins** [comment]
Great work @shraiysh - resolved by #392

**Comment by shraiysh** [comment]
Hey @rowanwins, this was my first pull request to an open source project. Thanks for your help.
